image: Ubuntu2004

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - java -jar ./artifacts/app-ibank-build-for-testers.jar &
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable

build_script:
  - chmod +x gradlew
  - ./gradlew test --info
